### ISSUE TITLE
Can I apply insets to lazy loaded map components?

### ISSUE THREAD

**Issue by MiSikora** [mapbox/mapbox-gl-native-android#178]
Since components like compass or attribution icon are now lazy loaded in `9.0.0` what is the way to apply appropriate insets to these views so they are in correct positions? Previously we just did `findViewById` and added inset listeners. Now it is not possible as views are not avaialble after inflation step. `fitsSystemWindows` is not enough as the map is not not drawn then under status and navigation bars.

**Comment by pengdev** [comment]
Thanks for the feedback! Mapbox exposes [UiSettings#setCompassViewMargins](https://docs.mapbox.com/android/api/map-sdk/8.6.2/com/mapbox/mapboxsdk/maps/UiSettings.html#setCompassMargins-int-int-int-int-) etc for adjusting the component insets. You can also config these options through [MapView XML attributes](https://docs.mapbox.com/android/maps/overview/#mapview-xml-attributes).

Another option would be to hold that config until the maps are ready, with a listener or so.

**Comment by MiSikora** [comment]
Hi, thank you for the response. I'm aware of these methods but this doesn't really fit our needs.

Bottom insets from navigation bar depend on a device (or even user preferences on the devices) and are dynamic due to stuff like keyboard. So we cannot apply them from `XML` attributes.

`setCompassViewMargins` is doable and we use it for setting static margins. Using it for dynamic insets requires unnecessary work for managing asynchronous fetch of a `MapboxMap` object and applying insets via [`OnApplyWindowInsetsListener`](https://developer.android.com/reference/androidx/core/view/OnApplyWindowInsetsListener).

Would it be possible to expose a callbacks on a `MapView` to inform when compass and other elemets are ready?

**Comment by MiSikora** [comment]
@pengdev Is there any non-workaround solution to this problem?

**Comment by pengdev** [comment]
Hi @MiSikora , I noticed we have removed the id of the view components. For the lazy loaded view components, we now have the [view tag](https://github.com/mapbox/mapbox-gl-native-android/blob/65cf1d1cc7a0d63d9cccc3fc27825d7ee24b3d80/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java#L203) instead of view ids, you could use [findViewWithTag](https://developer.android.com/reference/android/view/View#findViewWithTag(java.lang.Object)) instead of findViewById() when the views are injected. You could hold the set of the insets util the `Style.OnStyleLoaded` is called.

**Comment by MiSikora** [comment]
Oh, thanks. I didn't think of attaching listeners in `onStyleLoaded()`. I'll close this issue once I check and confirm that it works.

**Comment by MiSikora** [comment]
Ok, I can close as this solution works. Thank you for the help!
