### ISSUE TITLE
Throw exception if defaultEnabledValue is false

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-native-android#358]
Android equivalent of https://github.com/mapbox/mapbox-gl-native-ios/issues/212

Let's check the behavior on Android and adjust if needed.

cc @tobrun @knov @zugaldia

**Comment by 1ec5** [comment]
mapbox/mapbox-gl-native-ios#212 is specific to [a peculiarity of the Objective-C language](https://nshipster.com/bool/), that an NSDictionary represents Boolean values as NSNumber objects that evaluate to true even if they contain the number 0 meaning false. The only action here would be to make sure that any configuration option where the developer can provide their own end user opt-out is indeed an opt-out rather than an opt-in.

**Comment by Chaoba** [comment]
cc: @chriswu42
