### ISSUE TITLE
Binary size increase between v9.1.0 and v9.2.0

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-native-android#377]
Our latest minor release has increased in binary size due to a missing LTO configuration. We are working on resolving this and will publish a v9.2.1 patch asap.

cc @mapbox/maps-android

**Comment by tobrun** [comment]
Source of the issue is the migration of the jni C++ code from mapbox-gl-native to this repository in https://github.com/mapbox/mapbox-gl-native-android/issues/202. 

@tarigo I'm seeing a lot of differences between the old android.cmake and current one in terms of linker flags. Can we align those again and verify if we are getting the same binary sizes again as before?
