### ISSUE TITLE
Recent version android-v9.4.0 is still causing a crash on Android 11 when com.mapbox.mapboxsdk:mapbox-android-telemetry:6.1.0 is not included 

### ISSUE THREAD

**Issue by rpadma** [mapbox/mapbox-gl-native-android#543]
This is more of clarification question for this reply  https://github.com/mapbox/mapbox-gl-native-android/issues/425#issuecomment-680753940

I had tried to update the dependency version to `android-v9.4.0` and remove the `com.mapbox.mapboxsdk:mapbox-android-telemetry:6.1.0` as the latest [release note](https://github.com/mapbox/mapbox-gl-native-android/releases/tag/android-v9.4.0) states the telemetry version is been updated.

But I still see the same crash - 
```
java.lang.SecurityException: getDataNetworkTypeForSubscriber: uid 10265 does not have android.permission.READ_PHONE_STATE.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3356)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3500)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

```
@tobrun - Do i still need to include `implementation com.mapbox.mapboxsdk:mapbox-android-telemetry:6.1.0` even as part of the new version `android-v9.4.0` ?

**Comment by tobrun** [comment]
https://github.com/mapbox/mapbox-gl-native-android/blob/2d133aab7e0c0fd88dfe9b18ae154fae4290d1ab/gradle/dependencies.gradle#L11 is part of the v9.4.0 tag that triggered our continuous deployment of the release so 6.1.0 will be included. I validated Android 11 integration with targetSDK set to 30 and API 30 emulator in https://github.com/mapbox/mapbox-gl-native-android/issues/540 and didn't have any crash. 

Could you paste relevant part of your dependencies configuration? you can get that list with running `./gradlew app:dependencies`, where you replace app with your module name.

**Comment by rpadma** [comment]
@tobrun  - FYI. Is this an issue with refreshing gradle dependencies ? 🤔 
<img width="738" alt="Screen Shot 2020-08-28 at 8 36 34 AM" src="https://user-images.githubusercontent.com/5199471/91563145-64e79780-e90c-11ea-84cb-a23d4326f9d6.png">

**Comment by tobrun** [comment]
@rpadma thank you for following up, the first line indicates you are actually picking up v9.0.0 instead of v9.4.0 (all underlying shown dependencies match that version, these all have been updated since).

The root cause for this will probably related to us switching distribution from maven central to an own mapbox maven. Once you have that configured correctly it will pick up v9.4.0 instead of v9.0.0 (which I guess is currently pulled in transitively by another dependency hosted on maven central). 

Could you try adding the following configuration to your root build.gradle?

https://github.com/mapbox/mapbox-gl-native-android#setup-mapbox-access-token-for-dependency-download

**Comment by rpadma** [comment]
@tobrun - That works! Thank you for helping me out with the required information.

**Comment by soobasa** [comment]
@tobrun 
im still having issue ,  

dependencies :
`implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.2'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v9:0.12.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0'`
gradlew app:dependencies : 
`+--- com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.2
|    +--- com.mapbox.mapboxsdk:mapbox-android-telemetry-okhttp3:8.1.0
|    |    +--- com.squareup.okhttp3:okhttp:3.12.0 -> 3.14.4
|    |    |    \--- com.squareup.okio:okio:1.17.2
|    |    +--- androidx.core:core:1.5.0 (*)
|    |    +--- com.google.code.gson:gson:2.8.5 -> 2.8.6
|    |    +--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    |    +--- com.mapbox.mapboxsdk:mapbox-android-core:5.0.0
|    |    \--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    +--- com.mapbox.mapboxsdk:mapbox-android-core:5.0.0
|    +--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:5.3.0
|    |    \--- com.google.code.gson:gson:2.8.6
|    +--- com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0
|    |    +--- androidx.core:core:1.0.0 -> 1.5.0 (*)
|    |    \--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    +--- com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0
|    |    \--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    +--- com.mapbox.mapboxsdk:mapbox-android-sdk-gl-core:5.2.2
|    +--- com.mapbox.mapboxsdk:mapbox-sdk-turf:5.3.0
|    |    \--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:5.3.0 (*)
|    +--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    +--- androidx.fragment:fragment:1.0.0 -> 1.3.6 (*)
|    \--- com.squareup.okhttp3:okhttp:3.12.3 -> 3.14.4 (*)
+--- com.mapbox.mapboxsdk:mapbox-android-plugin-places-v9:0.12.0
|    +--- com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0 -> 9.6.2 (*)
|    +--- androidx.appcompat:appcompat:1.0.0 -> 1.3.1 (*)
|    +--- androidx.constraintlayout:constraintlayout:1.1.3 -> 2.1.0 (*)
|    +--- androidx.cardview:cardview:1.0.0 (*)
|    +--- androidx.recyclerview:recyclerview:1.0.0 -> 1.2.1 (*)
|    +--- androidx.legacy:legacy-support-v4:1.0.0
|    |    +--- androidx.core:core:1.0.0 -> 1.5.0 (*)
|    |    +--- androidx.media:media:1.0.0
|    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    |    |    +--- androidx.core:core:1.0.0 -> 1.5.0 (*)
|    |    |    \--- androidx.versionedparcelable:versionedparcelable:1.0.0 -> 1.1.1 (*)
|    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    |    +--- androidx.legacy:legacy-support-core-ui:1.0.0
|    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    |    |    +--- androidx.core:core:1.0.0 -> 1.5.0 (*)
|    |    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    |    |    +--- androidx.customview:customview:1.0.0 (*)
|    |    |    +--- androidx.viewpager:viewpager:1.0.0 (*)
|    |    |    +--- androidx.coordinatorlayout:coordinatorlayout:1.0.0 -> 1.1.0 (*)
|    |    |    +--- androidx.drawerlayout:drawerlayout:1.0.0 (*)
|    |    |    +--- androidx.slidingpanelayout:slidingpanelayout:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    |    |    |    +--- androidx.core:core:1.0.0 -> 1.5.0 (*)
|    |    |    |    \--- androidx.customview:customview:1.0.0 (*)
|    |    |    +--- androidx.interpolator:interpolator:1.0.0 (*)
|    |    |    +--- androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    |    |    |    +--- androidx.core:core:1.0.0 -> 1.5.0 (*)
|    |    |    |    \--- androidx.interpolator:interpolator:1.0.0 (*)
|    |    |    +--- androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    |    |    |    \--- androidx.core:core:1.0.0 -> 1.5.0 (*)
|    |    |    \--- androidx.cursoradapter:cursoradapter:1.0.0 (*)
|    |    \--- androidx.fragment:fragment:1.0.0 -> 1.3.6 (*)
|    +--- com.google.android.material:material:1.0.0 -> 1.4.0 (*)
|    +--- com.jakewharton.timber:timber:4.7.1
|    |    \--- org.jetbrains:annotations:16.0.1
|    +--- androidx.lifecycle:lifecycle-extensions:2.0.0
|    |    +--- androidx.lifecycle:lifecycle-runtime:2.0.0 -> 2.3.1 (*)
|    |    +--- androidx.arch.core:core-common:2.0.0 -> 2.1.0 (*)
|    |    +--- androidx.arch.core:core-runtime:2.0.0 -> 2.1.0 (*)
|    |    +--- androidx.fragment:fragment:1.0.0 -> 1.3.6 (*)
|    |    +--- androidx.lifecycle:lifecycle-common:2.0.0 -> 2.3.1 (*)
|    |    +--- androidx.lifecycle:lifecycle-livedata:2.0.0 -> 2.1.0 (*)
|    |    +--- androidx.lifecycle:lifecycle-process:2.0.0
|    |    |    \--- androidx.lifecycle:lifecycle-runtime:2.0.0 -> 2.3.1 (*)
|    |    +--- androidx.lifecycle:lifecycle-service:2.0.0 -> 2.1.0
|    |    |    \--- androidx.lifecycle:lifecycle-runtime:2.1.0 -> 2.3.1 (*)
|    |    \--- androidx.lifecycle:lifecycle-viewmodel:2.0.0 -> 2.3.1 (*)
|    +--- androidx.room:room-runtime:2.0.0 -> 2.2.5
|    |    +--- androidx.room:room-common:[2.2.5] -> 2.2.5
|    |    |    \--- androidx.annotation:annotation:1.1.0 -> 1.2.0
|    |    +--- androidx.sqlite:sqlite-framework:2.0.1 -> 2.1.0
|    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    |    |    \--- androidx.sqlite:sqlite:[2.1.0] -> 2.1.0
|    |    |         \--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|    |    +--- androidx.sqlite:sqlite:2.0.1 -> 2.1.0 (*)
|    |    \--- androidx.arch.core:core-runtime:2.0.1 -> 2.1.0 (*)
|    \--- com.mapbox.mapboxsdk:mapbox-sdk-services:5.1.0
|         +--- com.mapbox.mapboxsdk:mapbox-sdk-core:5.1.0
|         |    +--- com.google.code.gson:gson:2.8.6
|         |    +--- com.squareup.retrofit2:retrofit:2.7.1
|         |    |    \--- com.squareup.okhttp3:okhttp:3.14.4 (*)
|         |    +--- com.squareup.retrofit2:converter-gson:2.7.1
|         |    |    +--- com.squareup.retrofit2:retrofit:2.7.1 (*)
|         |    |    \--- com.google.code.gson:gson:2.8.5 -> 2.8.6
|         |    \--- com.squareup.okhttp3:logging-interceptor:3.12.7
|         |         \--- com.squareup.okhttp3:okhttp:3.12.7 -> 3.14.4 (*)
|         +--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:5.1.0 -> 5.3.0 (*)
|         +--- com.mapbox.mapboxsdk:mapbox-sdk-directions-models:5.1.0
|         |    +--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:5.1.0 -> 5.3.0 (*)
|         |    \--- androidx.annotation:annotation:1.0.0 -> 1.2.0
|         \--- com.mapbox.mapboxsdk:mapbox-sdk-directions-refresh-models:5.1.0
|              +--- com.mapbox.mapboxsdk:mapbox-sdk-directions-models:5.1.0 (*)
|              \--- androidx.annotation:annotation:1.0.0 -> 1.2.0
+--- com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0
|    +--- androidx.appcompat:appcompat:1.0.0 -> 1.3.1 (*)
|    \--- com.mapbox.mapboxsdk:mapbox-android-sdk:9.2.0 -> 9.6.2 (*)`


Compile /TARGET SDK VERSION : 
30 


TEST : Smamsun A20 Android 11 , Android Stuido Emulator API 30 


Error : 
`E/MapboxTelemetry: java.lang.ExceptionInInitializerError
E/libc++abi: terminating with uncaught exception of type jni::PendingJavaException`


NOTE : IF I set comile / sdk version  to 29 every thing is perfect but i cant release my app  update too googleplay  due to  new policies
