### ISSUE TITLE
A signed minifyEnabled release APK will cause VerifyError on Android 4.4

### ISSUE THREAD

**Issue by ystsoi** [mapbox/mapbox-gl-native-android#60]
If I build a signed release APK with minifyEnabled = true, using Gradle, the result APK will crash with VerifyError on Android 4.4, real device or emulator.

Mapbox SDK version: com.mapbox.mapboxsdk:mapbox-android-sdk:8.5.0

This issue can be solved by adding the following ProGuard rule from SoLoader:
https://github.com/facebook/SoLoader/blob/master/java/com/facebook/soloader/soloader.pro

It will be great if the rule can be added to MapboxGLAndroidSDK, so that developers do not need to add the rule themselves:
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/proguard-rules.pro

**Comment by LukasPaczos** [comment]
Hey @ystsoi, thanks for reporting the issue!

What's interesting, it seems to be caused by the optimization flag -  if your application's module release config defines:
```
proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
```
changing it to:
```
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
```
is going to resolve the issue as well. Check out this interesting in [this SO post](https://stackoverflow.com/a/56902474/9126211).

Anyway, let me go ahead and commit your suggestion which also gets the job done. Thanks!
