### ISSUE TITLE
MapboxMap.getStyle() On Null Object Reference

### ISSUE THREAD

**Issue by Pic2490** [mapbox/mapbox-gl-native-android#84]
Please help:
![Snip20191203_4](https://user-images.githubusercontent.com/58469026/70047391-d4e31000-157c-11ea-8556-57b2a6aa1f0e.png)
![Snip20191203_2](https://user-images.githubusercontent.com/58469026/70047461-f3e1a200-157c-11ea-8230-2995e01e23a2.png)

**Comment by LukasPaczos** [comment]
Hey @Pic2490, I don't see you assigning `mapboxMap` object returned in the `onMapReady` callback to the used `map` field, that's why the NPE is thrown.

Additionally, you should use the provided as the method argument `Style` object, or you can call:
```
mapboxMap.getStyle(new Style.OnStyleLoaded() {
  @Override
  public void onStyleLoaded(@NonNull Style style) {
    ...
  }
});
```

For future reference, this repo is for bug reports and feature requests only. If you're looking for assistance, reach out to [our support team](https://support.mapbox.com/hc/en-us) or the the [stackoverflow community](https://stackoverflow.com/questions/tagged/mapbox-android).
