### ISSUE TITLE
CameraMode.TRACKING not working in 8.1.0 and newer

### ISSUE THREAD

**Issue by Firzen7** [mapbox/mapbox-gl-native-android#98]
Hi,

locationComponent.setCameraMode(CameraMode.TRACKING) is not working in version 8.1.0 and newer.

I have tested these versions so far:
8.0.0 - working
8.0.1 - working
8.1.0 - **not working**
8.5.0 - **not working**
8.5.1 - **not working**
8.6.0-beta.1 - **not working**

Tested on Android 7.0 and 9.0, but I assume that Android version doesn't matter.

Could you please have a look at it?
Thanks!

**Comment by LukasPaczos** [comment]
Hey @Firzen7, thanks for reaching out! This is most likely because you're scheduling `MapboxMap` animations **after** setting the camera mode. See https://github.com/mapbox/mapbox-gl-native/issues/14538 and https://github.com/mapbox/mapbox-gl-native/pull/14745.

Closing, but please let us know if that wasn't the case and we can investigate further.

**Comment by Firzen7** [comment]
@LukasPaczos Thank you so much. I can't believe it was so simple to solve! Mapbox is amazing overall, thank you again!
